// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkpN1cR6-kQjrNIi5P3Wmk1OFSKl3qbMw',
    appId: '1:315738878852:web:712848d324b21f710823d1',
    messagingSenderId: '315738878852',
    projectId: 'responsi2irfan',
    authDomain: 'responsi2irfan.firebaseapp.com',
    storageBucket: 'responsi2irfan.firebasestorage.app',
    measurementId: 'G-EJ9YKVF3TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQnKJTeIym1Adc0O_oLYRodMRDb7BPOZg',
    appId: '1:315738878852:android:c03ed5f1b5a32d8c0823d1',
    messagingSenderId: '315738878852',
    projectId: 'responsi2irfan',
    storageBucket: 'responsi2irfan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXYV_jOdO8-l3VmTHueTzQvM62IVNaqJU',
    appId: '1:315738878852:ios:d0acc51798e40efd0823d1',
    messagingSenderId: '315738878852',
    projectId: 'responsi2irfan',
    storageBucket: 'responsi2irfan.firebasestorage.app',
    iosBundleId: 'com.example.responsi2MobilePaket3H1d023023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXYV_jOdO8-l3VmTHueTzQvM62IVNaqJU',
    appId: '1:315738878852:ios:d0acc51798e40efd0823d1',
    messagingSenderId: '315738878852',
    projectId: 'responsi2irfan',
    storageBucket: 'responsi2irfan.firebasestorage.app',
    iosBundleId: 'com.example.responsi2MobilePaket3H1d023023',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkpN1cR6-kQjrNIi5P3Wmk1OFSKl3qbMw',
    appId: '1:315738878852:web:b192fffd9baa2db40823d1',
    messagingSenderId: '315738878852',
    projectId: 'responsi2irfan',
    authDomain: 'responsi2irfan.firebaseapp.com',
    storageBucket: 'responsi2irfan.firebasestorage.app',
    measurementId: 'G-3J1763XHS9',
  );
}
